### PR TITLE
Add GitHub Actions workflow for Checkstyle. Add workflow to run Check…

### LINKED ISSUE #2: [C4GT Community]: Configure GitHub Actions for Checkstyle code formatting and vulnerability scanning in AMRIT API repositories
## Description

To maintain code quality and security for [AMRIT API repositories](https://github.com/orgs/PSMRI/repositories?q=-API), we need to set up GitHub Actions workflows that perform code formatting checks using Checkstyle and vulnerability scanning with OWASP Dependency-Check. These workflows should ensure that code formatting issues are detected for changed files in pull requests, and vulnerability scanning is conducted when pom.xml changes. Merging of pull requests should be restricted unless these checks pass.

#### What You Will Learn:
As an intern, you will:
- Gain experience with GitHub Actions and CI/CD pipelines.
- Learn how to configure static code analysis and security scanning in Java projects.
- Develop skills in enforcing code quality and security practices.
- Work collaboratively with developers to ensure high standards in code quality.

#### Desired Skills:

- Basic knowledge of Java and Maven.
- Familiarity with GitHub Actions and CI/CD workflows.
- Understanding of static code analysis tools.
- Eagerness to learn and implement best practices in code quality and security.

### Goals

Setup GitHub Actions for Checkstyle:

- [ ] Create a GitHub Actions workflow to run Checkstyle on pull requests.
- [ ] Configure the workflow to check code formatting for changed files only.
- [ ] Ensure that merging is blocked unless Checkstyle checks pass.

Setup GitHub Actions for OWASP Dependency-Check:

- Create a GitHub Actions workflow to run OWASP Dependency-Check.
- Configure the workflow to trigger only when pom.xml or pom.xml files change.
- Ensure that merging is blocked unless the vulnerability scan passes.

### Expected Outcome

Fully functional GitHub Actions workflows that automatically check code formatting with Checkstyle and perform vulnerability scanning with OWASP Dependency-Check. These workflows will ensure that pull requests meet coding standards and are free of known vulnerabilities before merging.

### Acceptance Criteria

Checkstyle Workflow:

- Checkstyle runs on changed files in pull requests.
- Merging is blocked unless Checkstyle checks pass without errors.

OWASP Dependency-Check Workflow:

- OWASP Dependency-Check runs when pom.xml changes.
- Merging is blocked unless no critical vulnerabilities are found.

### Implementation Details

https://github.com/checkstyle/checkstyle
https://central.sonatype.com/artifact/org.owasp/dependency-check-maven/8.4.0/overview
https://github.com/marketplace/actions/dependency-check
https://github.com/marketplace?query=checkstyle

### Mockups/Wireframes

NA

### Product Name

AMRIT

### Organisation Name

Piramal Swasthya Management Research Institute

### Domain

Healthcare

### Tech Skills Needed

CI/CD, Debugging, DevOps, Java, Security, Spring Boot

### Mentor(s)

@drtechie 

### Complexity

Medium

### Category

CI/CD, Documentation, Delpoyment

### PR DESCRIPTION
**Pull request by harshsennnn**
Fixes #2

📋 Description

This PR addresses the issue raised in #2, where a GitHub Actions workflow for running Checkstyle on pull requests was needed. I have implemented the workflow to check Java code formatting using Checkstyle and integrated it with the pull request process. This change ensures that code formatting issues are detected and reported for any changed files in pull requests.

Since the issue was not assigned to me, I took the initiative to create this workflow to improve code quality by automatically checking for formatting violations.

Kindly assign the issue to me and review the pr

## Summary by CodeRabbit

- **New Features**
	- Introduced an automated workflow for checking Java code style using Checkstyle on pull requests.
  
- **Chores**
	- Added a new GitHub Actions workflow file to enhance code quality checks.

### CODE REVIEW

**Comment by drtechie** [comment]
@harshsennnn the checkstyle checks have to added to AMRIT API repositories as mentioned in the description and comments of the original issue. 
Closing this PR.

**Comment by drtechie** [comment]
You can start with https://github.com/PSMRI/HWC-API
If you have doubts, ping me on Discord, ID: drtechie.

**Comment by harshsennnn** [comment]
it have to be added to each repo or the only one you've shared here ?

**Comment by Sneha6003** [comment]
@all-contributors please add @harshsennnn  for code

**Comment by Sneha6003** [comment]
@all-contributors please add @harshsennnn  for code

**Comment by Sneha6003** [comment]
@all-contributors please add @harshsennnn for code

**Comment by Sneha6003** [comment]
@all-contributors please add @harshsennnn for code

**Comment by Sneha6003** [comment]
@all-contributors please add @harshsennnn for Tests

**Pull request closed without merging**
